server {
  listen       80;
  server_name  _;
  root   /usr/share/nginx/html/studio;
  index  index.html;

  location / {
    try_files $uri $uri/ /studio/index.html;
  }

  location /studio/ {
    try_files $uri $uri/ /studio/index.html;
  }
}
